#!/usr/bin/python

import os
from settings import DATABASES
from pprint import pprint

def read(msg, default=None, options=None):
    if options is not None:
        msg = "%s [%s]" % (msg, ', '.join(options))
    if default is None:
        msg = "%s: " % msg
    else:
        msg = "%s (%s): " % (msg, default)

    user_input = raw_input(msg)
    if user_input == "" and default is not None:
        user_input = default

    if options is not None and user_input not in options:
        return read(msg, default=default, options=options)
    return user_input

project_name = os.getcwd().split("/")[-1]

config_name = read("Configuration name","default")
engine = read("Database Engine",
             options=['postgresql_psycopg2', 'postgresql', 'sqlite3', 'oracle', 'mysql'],
             default="mysql")

if engine == "sqlite3":
    name_msg = "Path to database"
    name_default = "./%s_database.sqlite3" % project_name
    user = ""
    password = ""
    host = ""
    port = ""
else:
    name_msg = "Database name"
    name_default = project_name

name = read(name_msg, default=name_default)

if engine != "sqlite3":
    user = read("Database user", default=project_name)
    password = read("Database password", default=project_name)
    host = read("Database host (localhost)")
    port = read("Database port (use default)")

db_config = {
        'ENGINE' : "django.db.backends.%s" % engine,
        'NAME' : name,
        'USER' : user,
        'PASSWORD' : password,
        'HOST' : host,
        'PORT' : port,
}

DATABASES[config_name] = db_config

def prepr(var):
    out = repr(var).replace("{","{\n").replace(",",",\n").replace("}","}\n")
    return out


f = file("./local_databases.py","w")
f.write("DATABASES = "+prepr(DATABASES))
f.close()
